### ISSUE TITLE
it cannot support spigot 1.18.2!

### ISSUE THREAD

**Issue by 982074664** [NichtStudioCode/MiniatureBlocks#13] opened 2022-08-10 12:47 UTC
it cannot support spigot 1.18.2!
put resource to the cilent but it says that resoucespack is not reday!

**Comment by NichtStudioCode** [comment] 2022-08-10 12:51
Again, duplicate of #11.

As stated on the spigot page, MiniatureBlocks only runs on 1.14.x - 1.18.1

**Closed** 2022-08-10 12:52 UTC
Labels: duplicate

**Comment by 982074664** [comment] 2022-08-10 13:00
When it will support 1.18.2? I really need it,please. I can't speak English well,sorry
